# Box size
BOX_HEIGHT = 100 
BOX_WIDTH = 200

NUMBER_OF_SPAWN_ATTEMPS = 10

# Targets
TARGET_SPEED = 30
TARGET_RADIUS = 10

# Spawn time
SPAWN_TIME_INTERVAL = 0.5 
SPAWN_TIME_RANDOM_OFFSET = 0.2 

# Trajectory
TRAJECTORY_PROBABILITIES = [
    ('Linear', 0.5),
    ('HorizontalZigZag', 0.2),
    ('VerticalZigZag', 0.2),
    ('Spiral', 0.1),
]
TRAJECTORY_SCALE = 10
TRAJECTORY_PERIOD = 4

# Rotation
ADD_ROTATION_PROBABILITY = 0.5
ROTATION_TIME = 0.5
ROTATION_PERIOD = 3

